name: Publish Python Package to PyPI

on:
  release:
    types: [created]
  push:
    branches: [main]

jobs:
  build-and-publish:
    name: Build and publish Python package
    runs-on: ubuntu-latest
    environment: production  # 👈 Required if your variable is scoped to this environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ vars.PYPI_API_TOKEN }}  # 👈 Uses environment variable
        run: |
          twine upload dist/*
